version: "3.8"

services:
  # BigTable Emulator
  # https://cloud.google.com/bigtable/docs/emulator
  bigtable:
#    image: google/cloud-sdk:latest
    image: gcr.io/google.com/cloudsdktool/cloud-sdk:emulators
#    command: gcloud beta emulators bigtable start --host-port=0.0.0.0:8086
    command: gcloud beta emulators bigtable start --host-port=bigtable:8086
    ports:
      - 8086:8086

  pythonapp:
    build: .
#    image: foo
    depends_on:
      - bigtable
    environment:
      - BIGTABLE_EMULATOR_HOST=bigtable:8086
    command: python app/main.py
